module.exports = {
    social: require("./modules/social"),
    inquiry: require("./modules/inquiry"),
    ai: require("./modules/ai"),
    tools: require("./modules/tools"),
    shopping: require("./modules/shopping"),
    news: require("./modules/news"),
    movie: require("./modules/movie"),
    price: require("./modules/price"),
    fun: require("./modules/fun"),
    image: require("./modules/image"),
    googlePlay: require("./modules/googlePlay"),
    video: require("./modules/video"),
    myket: require("./modules/myket"),
    dictionary: require("./modules/dictionary"),
    drug: require("./modules/drug"),
    farsroid: require("./modules/farsroid"),
    sport: require("./modules/sport"),
    wikipedia: require("./modules/wikipedia")
}